services:
  backend:
    container_name: jidoka_app_dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    container_name: jidoka_worker_dev
    volumes:
      - ./backend:/app
    command: taskiq worker src.core.broker:broker src.worker

  db:
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    ports:
      - "6379:6379"
